server:
  port: 7070

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: cliente
          uri: lb://cliente
          predicates:
            - paths=/cliente/**
        - id: produto
          uri: lb://produto
          predicates:
            - paths=/produto/**